package com.astrolog.util;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.util.List;
import java.util.Map;

public final class ExportUtil {

    private ExportUtil() {}

    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
    private static final Font SUBTITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
    private static final Font HEADING_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
    private static final Font NORMAL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 12);
    private static final Font SMALL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10);
    private static final Font SMALL_ITALIC = FontFactory.getFont(FontFactory.HELVETICA, Font.ITALIC, 10);

    @SuppressWarnings("unchecked")
    public static void exportPdfReport(Map<String, Object> params, String outputPath)
            throws Exception {
        Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
        PdfWriter.getInstance(doc, new FileOutputStream(outputPath));
        doc.open();

        // Title
        Paragraph title = new Paragraph("AstroLog Annual Observation Report", TITLE_FONT);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);
        doc.add(new Paragraph(" "));

        // Info line
        String info = "Observer: " + params.get("USERNAME")
            + "    |    Year: " + params.get("YEAR")
            + "    |    Generated: " + params.get("GENERATED_AT");
        Paragraph infoPara = new Paragraph(info, NORMAL_FONT);
        infoPara.setAlignment(Element.ALIGN_CENTER);
        doc.add(infoPara);
        doc.add(new Paragraph(" "));

        // --- Annual Summary ---
        Paragraph summaryTitle = new Paragraph("Annual Summary", SUBTITLE_FONT);
        doc.add(summaryTitle);
        doc.add(new Paragraph(" "));

        PdfPTable statsTable = new PdfPTable(2);
        statsTable.setWidthPercentage(80);
        addStatRow(statsTable, "Total Observations", String.valueOf(params.get("TOTAL_OBS")));
        addStatRow(statsTable, "Distinct Bodies", String.valueOf(params.get("DISTINCT_BODIES")));
        addStatRow(statsTable, "Equipment Used", String.valueOf(params.get("TOTAL_EQUIP")));
        doc.add(statsTable);
        doc.add(new Paragraph(" "));

        // --- Body Type Distribution ---
        Map<String, Long> typeDist = (Map<String, Long>) params.get("TYPE_DIST");
        if (typeDist != null && !typeDist.isEmpty()) {
            Paragraph typeTitle = new Paragraph("Body Type Distribution", SUBTITLE_FONT);
            doc.add(typeTitle);
            doc.add(new Paragraph(" "));

            PdfPTable typeTable = new PdfPTable(2);
            typeTable.setWidthPercentage(70);
            typeTable.addCell(headerCell("Type"));
            typeTable.addCell(headerCell("Count"));
            for (Map.Entry<String, Long> e : typeDist.entrySet()) {
                typeTable.addCell(dataCell(e.getKey()));
                typeTable.addCell(dataCell(String.valueOf(e.getValue())));
            }
            doc.add(typeTable);
            doc.add(new Paragraph(" "));
        }

        // --- Equipment Ranking ---
        List<Map.Entry<String, Long>> topEquip =
            (List<Map.Entry<String, Long>>) params.get("TOP_EQUIP");
        if (topEquip != null && !topEquip.isEmpty()) {
            Paragraph equipTitle = new Paragraph("Equipment Ranking (Top 10)", SUBTITLE_FONT);
            doc.add(equipTitle);
            doc.add(new Paragraph(" "));

            PdfPTable equipTable = new PdfPTable(2);
            equipTable.setWidthPercentage(70);
            equipTable.addCell(headerCell("Equipment"));
            equipTable.addCell(headerCell("Times Used"));
            for (Map.Entry<String, Long> e : topEquip) {
                equipTable.addCell(dataCell(e.getKey()));
                equipTable.addCell(dataCell(String.valueOf(e.getValue())));
            }
            doc.add(equipTable);
            doc.add(new Paragraph(" "));
        }

        // Footer
        Paragraph footer = new Paragraph(
            "Generated by AstroLog v1.0 - Astronomical Observation Log & Star Management",
            SMALL_ITALIC);
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);

        doc.close();
    }

    private static PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADING_FONT));
        cell.setBorder(Rectangle.BOTTOM);
        cell.setPadding(5);
        cell.setGrayFill(0.92f);
        return cell;
    }

    private static PdfPCell dataCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, NORMAL_FONT));
        cell.setBorder(Rectangle.BOTTOM);
        cell.setPadding(5);
        return cell;
    }

    private static void addStatRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, HEADING_FONT));
        labelCell.setBorder(Rectangle.NO_BORDER);
        labelCell.setPadding(6);
        PdfPCell valueCell = new PdfPCell(new Phrase(value, HEADING_FONT));
        valueCell.setBorder(Rectangle.NO_BORDER);
        valueCell.setPadding(6);
        valueCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    public static void exportPdfCert(Map<String, Object> params, String outputPath)
            throws Exception {
        Document doc = new Document(PageSize.A4.rotate(), 50, 50, 60, 60);
        PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(outputPath));
        doc.open();

        // Decorative border
        PdfContentByte cb = writer.getDirectContent();
        cb.setLineWidth(2);
        cb.rectangle(30, 30, doc.getPageSize().getWidth() - 60,
            doc.getPageSize().getHeight() - 60);
        cb.stroke();
        cb.setLineWidth(1);
        cb.rectangle(35, 35, doc.getPageSize().getWidth() - 70,
            doc.getPageSize().getHeight() - 70);
        cb.stroke();

        doc.add(new Paragraph(" "));
        doc.add(new Paragraph(" "));

        Font certTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 28);
        Paragraph certTitle = new Paragraph("Messier Marathon", certTitleFont);
        certTitle.setAlignment(Element.ALIGN_CENTER);
        doc.add(certTitle);

        Paragraph certSub = new Paragraph("Completion Certificate", TITLE_FONT);
        certSub.setAlignment(Element.ALIGN_CENTER);
        doc.add(certSub);

        doc.add(new Paragraph(" "));
        doc.add(new Paragraph(" "));

        Font certBodyFont = FontFactory.getFont(FontFactory.HELVETICA, 16);
        Paragraph certify = new Paragraph("This certifies that", certBodyFont);
        certify.setAlignment(Element.ALIGN_CENTER);
        doc.add(certify);

        doc.add(new Paragraph(" "));

        Font nameFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
        Paragraph namePara = new Paragraph(String.valueOf(params.get("USERNAME")), nameFont);
        namePara.setAlignment(Element.ALIGN_CENTER);
        doc.add(namePara);

        doc.add(new Paragraph(" "));

        Paragraph achieved = new Paragraph(
            "has successfully observed all 110 Messier objects", certBodyFont);
        achieved.setAlignment(Element.ALIGN_CENTER);
        doc.add(achieved);

        doc.add(new Paragraph(" "));
        doc.add(new Paragraph(" "));

        Font detailFont = FontFactory.getFont(FontFactory.HELVETICA, 14);
        Paragraph detail = new Paragraph(
            "Completed: " + params.get("COMPLETED_COUNT") + " / " + params.get("TOTAL_COUNT")
            + "    |    Date: " + params.get("COMPLETED_AT"), detailFont);
        detail.setAlignment(Element.ALIGN_CENTER);
        doc.add(detail);

        doc.add(new Paragraph(" "));
        doc.add(new Paragraph(" "));

        Font memorialFont = FontFactory.getFont(FontFactory.HELVETICA, Font.ITALIC, 14);
        Paragraph memorial = new Paragraph(
            "Issued in recognition of this outstanding achievement", memorialFont);
        memorial.setAlignment(Element.ALIGN_CENTER);
        doc.add(memorial);

        doc.add(new Paragraph(" "));
        doc.add(new Paragraph(" "));

        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 11);
        Paragraph footer = new Paragraph(
            "AstroLog v1.0 - Astronomical Observation Log & Star Management", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);

        doc.close();
    }
}
